### ISSUE TITLE
Well

### ISSUE THREAD

**Issue by auroustv** [AurousGroup/frontend#3]
Nice to meet you. You are VERY brave for uploading this code.

I don't know if you noticed but this app lets you download copyright material without the permission of the artist or discography. In other words, you are encouraging piracy. Sorry but this is ilegal in most countries, such as United States of America.

Please remove this content or some piracy group would take legal action.

Let me know if you have any question regarding copyright laws.

**Comment by Codeusa** [comment]
Are you really pretending to be @AurousGroup/owners 

What is wrong with you?

**Comment by RoxKilly** [comment]
@Codeusa You're right about the copyright issue but that hasn't stopped monied interests in the past as I'm sure you know. Regardless of the tone the OP took, I hope you are considering alternative hosting options for your code because github has a history of closing down repos when copyright lawyers come calling, even on projects that do not infringe.  

That's exactly [what happened](https://torrentfreak.com/mpaa-pulls-popcorn-time-off-github-140711/) to Popcorn Time, another project that was just front end code. Now they host their git repo on [their own site](https://git.popcorntime.io/groups/popcorntime).  It sucks that we live in a wold where money often trumps rights but I don't think anyone would be surprised if github took your project down within a month. I hope I'm wrong.

**Comment by Yann-P** [comment]
@RoxKilly True. And since the project has been announced quite a while ago, they must be well-prepared and it will go fast.

**Comment by Draxler** [comment]
@auroustv 
______________________________________________
Are you mentaly chalanged ? First you pretend to be the Aurous Group with your fake aurous sites you opened and then also offer this app your self. And now you come here and start with this Copyrightt BS your self ? I don't like to be the 1 who bring the bad news bad you need to see somaone like asap. The you contradicting your self is unhurd off..

**Comment by Draxler** [comment]
@auroustv

This is ilegal in **most** *countries*, **such as United States of America.**

Most country such as USA are very few coutry and even most of these country were bullied and pressured by US with they CopyRight BS. 
In WW2 we had Nazis Germany for world to vorry about , now in modern time we have USA.
